
export const sample_players: any[] = [
  {
    id: 1,
    name: 'Lionel Messi',
    age: 36,
    img: './assets/messi.jpg',
    position: 'CF',
    overallRating: 93,
    skills: {
      pace: 85,
      stamina: 75,
      strength: 65,
      agility: 95,
      balance: 95,
      shooting: 92,
      passing: 91,
      dribbling: 96,
      ballControl: 95,
      crossing: 85,
      heading: 70,
      tackling: 35,
      marking: 30,
      interception: 40,
      diving: 0,
      handling: 0,
      kicking: 0,
      reflexes: 0,
      positioning: 0,
      vision: 94,
      composure: 96,
      leadership: 85,
      teamwork: 88,
      workRate: {
        attack: 90,
        defense: 45
      }
    },
    form: 90,
    isInjured: false,
    teamId: 1
  },
  {
    id: 2,
    name: 'Cristiano Ronaldo',
    age: 39,
    img: './assets/messi.jpg',
    position: 'CF',
    overallRating: 91,
    skills: {
      pace: 85,
      stamina: 80,
      strength: 85,
      agility: 80,
      balance: 70,
      shooting: 93,
      passing: 82,
      dribbling: 88,
      ballControl: 90,
      crossing: 80,
      heading: 95,
      tackling: 35,
      marking: 30,
      interception: 40,
      diving: 0,
      handling: 0,
      kicking: 0,
      reflexes: 0,
      positioning: 0,
      vision: 84,
      composure: 95,
      leadership: 90,
      teamwork: 85,
      workRate: {
        attack: 90,
        defense: 40
      }
    },
    form: 85,
    isInjured: false,
    teamId: 1
  },
  {
    id: 3,
    name: 'Neymar Jr.',
    age: 32,
    img: '',
    position: 'RW',
    overallRating: 89,
    skills: {
      pace: 91,
      stamina: 75,
      strength: 60,
      agility: 93,
      balance: 90,
      shooting: 85,
      passing: 87,
      dribbling: 94,
      ballControl: 92,
      crossing: 83,
      heading: 60,
      tackling: 40,
      marking: 35,
      interception: 45,
      diving: 0,
      handling: 0,
      kicking: 0,
      reflexes: 0,
      positioning: 0,
      vision: 88,
      composure: 90,
      leadership: 70,
      teamwork: 80,
      workRate: {
        attack: 85,
        defense: 40
      }
    },
    form: 80,
    isInjured: false,
    teamId: 1
  },
  {
    id: 4,
    name: 'Kevin De Bruyne',
    age: 32,
    img: '',
    position: 'AM',
    overallRating: 91,
    skills: {
      pace: 76,
      stamina: 80,
      strength: 75,
      agility: 78,
      balance: 82,
      shooting: 85,
      passing: 92,
      dribbling: 88,
      ballControl: 90,
      crossing: 90,
      heading: 70,
      tackling: 60,
      marking: 55,
      interception: 65,
      diving: 0,
      handling: 0,
      kicking: 0,
      reflexes: 0,
      positioning: 0,
      vision: 95,
      composure: 88,
      leadership: 85,
      teamwork: 90,
      workRate: {
        attack: 85,
        defense: 70
      }
    },
    form: 85,
    isInjured: false,
    teamId: 2
  },
  {
    id: 5,
    name: 'Virgil van Dijk',
    age: 32,
    img: '',
    position: 'CB',
    overallRating: 89,
    skills: {
      pace: 77,
      stamina: 85,
      strength: 93,
      agility: 70,
      balance: 75,
      shooting: 60,
      passing: 75,
      dribbling: 70,
      ballControl: 75,
      crossing: 60,
      heading: 90,
      tackling: 90,
      marking: 92,
      interception: 88,
      diving: 0,
      handling: 0,
      kicking: 0,
      reflexes: 0,
      positioning: 0,
      vision: 75,
      composure: 85,
      leadership: 90,
      teamwork: 88,
      workRate: {
        attack: 60,
        defense: 90
      }
    },
    form: 90,
    isInjured: false,
    teamId: 2
  }
];

export const sample_users: any[] = [
  {
    name: 'John Doe',
    email: 'john@gmail.com',
    password: '12345',
    address: 'Toronto On',
    isAdmin: true, 
  },
  {
    name: 'Jane Doe',
    email: 'jane@gmail.com',
    password: '12345',
    address: 'Shanghai',
    isAdmin: false, 
  },
];