
export const sample_players: any[] = [
  {
    id: 1,
    name: 'Lionel Messi',
    age: 36,
    img: '',
    salary: 100000,
    contractExp: '1/1/1988',
    position: 'CF',
    overallRating: 93,
    skills: {
      pace: 85,
      stamina: 75,
      strength: 65,
      agility: 95,
      balance: 95,
      shooting: 92,
      passing: 91,
      dribbling: 96,
      ballControl: 95,
      crossing: 85,
      heading: 70,
      tackling: 35,
      marking: 30,
      interception: 40,
      diving: 0,
      handling: 0,
      kicking: 0,
      reflexes: 0,
      positioning: 0,
      vision: 94,
      composure: 96,
      leadership: 85,
      teamwork: 88,
      workRate: {
        attack: 90,
        defense: 45
      }
    },
    form: 90,
    isInjured: false,
    teamId: 1
  },
  {
    id: 2,
    name: 'Cristiano Ronaldo',
    age: 39,
    img: '',
    salary: 100000,
    contractExp: '1/1/1988',
    position: 'CF',
    overallRating: 91,
    skills: {
      pace: 85,
      stamina: 80,
      strength: 85,
      agility: 80,
      balance: 70,
      shooting: 93,
      passing: 82,
      dribbling: 88,
      ballControl: 90,
      crossing: 80,
      heading: 95,
      tackling: 35,
      marking: 30,
      interception: 40,
      diving: 0,
      handling: 0,
      kicking: 0,
      reflexes: 0,
      positioning: 0,
      vision: 84,
      composure: 95,
      leadership: 90,
      teamwork: 85,
      workRate: {
        attack: 90,
        defense: 40
      }
    },
    form: 85,
    isInjured: false,
    teamId: 1
  },
  {
    id: 3,
    name: 'Neymar Jr.',
    age: 32,
    img: '',
    salary: 100000,
    contractExp: '1/1/1988',
    position: 'RW',
    overallRating: 89,
    skills: {
      pace: 91,
      stamina: 75,
      strength: 60,
      agility: 93,
      balance: 90,
      shooting: 85,
      passing: 87,
      dribbling: 94,
      ballControl: 92,
      crossing: 83,
      heading: 60,
      tackling: 40,
      marking: 35,
      interception: 45,
      diving: 0,
      handling: 0,
      kicking: 0,
      reflexes: 0,
      positioning: 0,
      vision: 88,
      composure: 90,
      leadership: 70,
      teamwork: 80,
      workRate: {
        attack: 85,
        defense: 40
      }
    },
    form: 80,
    isInjured: false,
    teamId: 1
  },
  {
    id: 4,
    name: 'Kevin De Bruyne',
    age: 32,
    img: '',
    salary: 100000,
    contractExp: '1/1/1988',
    position: 'AM',
    overallRating: 91,
    skills: {
      pace: 76,
      stamina: 80,
      strength: 75,
      agility: 78,
      balance: 82,
      shooting: 85,
      passing: 92,
      dribbling: 88,
      ballControl: 90,
      crossing: 90,
      heading: 70,
      tackling: 60,
      marking: 55,
      interception: 65,
      diving: 0,
      handling: 0,
      kicking: 0,
      reflexes: 0,
      positioning: 0,
      vision: 95,
      composure: 88,
      leadership: 85,
      teamwork: 90,
      workRate: {
        attack: 85,
        defense: 70
      }
    },
    form: 85,
    isInjured: false,
    teamId: 2
  },
  {
    id: 5,
    name: 'Virgil van Dijk',
    age: 32,
    img: '',
    salary: 100000,
    contractExp: '1/1/1988',
    position: 'CB',
    overallRating: 89,
    skills: {
      pace: 77,
      stamina: 85,
      strength: 93,
      agility: 70,
      balance: 75,
      shooting: 60,
      passing: 75,
      dribbling: 70,
      ballControl: 75,
      crossing: 60,
      heading: 90,
      tackling: 90,
      marking: 92,
      interception: 88,
      diving: 0,
      handling: 0,
      kicking: 0,
      reflexes: 0,
      positioning: 0,
      vision: 75,
      composure: 85,
      leadership: 90,
      teamwork: 88,
      workRate: {
        attack: 60,
        defense: 90
      }
    },
    form: 90,
    isInjured: false,
    teamId: 2
  }
];

export const sample_users: any[] = [
  {
    name: 'John Doe',
    email: 'john@gmail.com',
    password: '12345',
    address: 'Toronto On',
    isAdmin: true, 
  },
  {
    name: 'Jane Doe',
    email: 'jane@gmail.com',
    password: '12345',
    address: 'Shanghai',
    isAdmin: false, 
  },
];

export const popularLastNames: { [country: string]: string[] } = {
  "Germany": ["Müller", "Schmidt", "Schneider", "Fischer", "Weber", "Meyer", "Wagner", "Becker", "Hoffmann", "Schäfer", "Koch", "Richter", "Klein", "Schwarz", "Zimmermann", "Braun", "Schultz", "Hofmann", "Lange", "Werner", "Mayer", "Kramer", "Schuster", "Jäger", "Horn"],
  "France": ["Martin", "Bernard", "Dubois", "Thomas", "Robert", "Richard", "Petit", "Durand", "Leroy", "Moreau", "Simon", "Laurent", "Michel", "Carpentier", "Lemoine", "Garnier", "Pires", "Rousseau", "Dumont", "Gauthier", "Benoit", "Lemoine", "Lucas", "Bouchard", "Perrot"],
  "Italy": ["Rossi", "Russo", "Ferrari", "Esposito", "Bianchi", "Romano", "Colombo", "Ricci", "Marino", "Greco", "Bruno", "Galli", "Conti", "Costa", "Fontana", "Giordano", "Rizzo", "Moretti", "Mancini", "Lombardi", "Farina", "Gentile", "Caruso", "Barbieri", "Santoro"],
  "Spain": ["García", "Fernández", "González", "Rodríguez", "López", "Martínez", "Sánchez", "Pérez", "Gómez", "Vázquez", "Moreno", "Molina", "Jiménez", "Alonso", "Romero", "Morales", "Hernández", "Muñoz", "Cruz", "Ortega", "Ruiz", "Castro", "Gutiérrez", "Reyes", "Marín"],
  "United Kingdom": ["Smith", "Jones", "Williams", "Taylor", "Brown", "Wilson", "Johnson", "Roberts", "Thompson", "White", "Walker", "Wright", "Green", "Harris", "Clark", "Lewis", "Young", "Hall", "Allen", "King", "Scott", "Adams", "Baker", "Mitchell", "Evans"],
  "Portugal": ["Silva", "Santos", "Ferreira", "Pereira", "Oliveira", "Costa", "Ribeiro", "Martins", "Gonçalves", "Lopes", "Almeida", "Mendes", "Carvalho", "Pinto", "Silveira", "Sousa", "Oliveira", "Azevedo", "Machado", "Nunes", "Barbosa", "Rodrigues", "Simões", "Teixeira", "Serrano"],
  "Netherlands": ["Jansen", "De Jong", "Van Dijk", "Bakker", "Van den Berg", "Jansen", "Huisman", "Van der Meer", "De Vries", "Smit", "Meijer", "Vermeulen", "Mulder", "Bos", "Willems", "Visser", "Van Leeuwen", "Koster", "Van der Linden", "Smits", "Groot", "Kuipers", "Vink", "De Graaf", "De Lange"],
  "Belgium": ["Jansen", "Peeters", "Dubois", "Lefèvre", "Jacobs", "Maes", "Leman", "Huygens", "Janssens", "Van den Broeck", "Claes", "Mertens", "Beyers", "Verhoeven", "Vermeulen", "Boone", "Benoit", "Serruys", "Nijs", "Janssens", "Rousseau", "Geldof", "Vandermeersch", "Hendrickx", "Brucker"],
  "Sweden": ["Andersson", "Johansson", "Karlsson", "Nilsson", "Eriksson", "Larsson", "Olsen", "Svensson", "Gustafsson", "Pettersson", "Jansson", "Hansson", "Bergström", "Lindberg", "Lindström", "Mårtensson", "Håkansson", "Fransson", "Nilsson", "Danielsson", "Lind", "Persson", "Kling", "Söderström"],
  "Norway": ["Hansen", "Johansen", "Olsen", "Larsen", "Andersen", "Berg", "Nilsen", "Haugen", "Rasmussen", "Sørensen", "Eriksen", "Pettersen", "Jensen", "Karlsson", "Gundersen", "Strand", "Lind", "Sivertsen", "Tveit", "Røed", "Bakken", "Holm", "Kleven", "Haugland", "Bjørnsen"],
  "Denmark": ["Jensen", "Nielsen", "Hansen", "Pedersen", "Andersen", "Christensen", "Jørgensen", "Madsen", "Petersen", "Rasmussen", "Højbjerg", "Juhl", "Kjær", "Sørensen", "Bengtsson", "Mikkelsen", "Wagner", "Thomsen", "Christiansen", "Saxberg", "Jørgensen", "Olsson", "Jensen", "Holm", "Frandsen"],
  "Finland": ["Korhonen", "Virtanen", "Mäkinen", "Hämäläinen", "Järvinen", "Heikkinen", "Lehtonen", "Salminen", "Koski", "Laine", "Huttunen", "Laitinen", "Räsänen", "Ojala", "Kallio", "Pekka", "Koskinen", "Rautiainen", "Koskinen", "Timonen", "Kangaspunta", "Puustinen", "Suominen", "Niemi", "Mäkelä"],
  "Iceland": ["Jónsson", "Sigurðsson", "Guðmundsson", "Magnússon", "Ólafsson", "Bergsson", "Einarsson", "Pálsson", "Ragnarsson", "Andrésdóttir", "Ásgeirsdóttir", "Bjarni", "Friðriksson", "Hákonsson", "Haraldsson", "Óskarsdóttir", "Stefánsson", "Tómasdóttir", "Jónsdóttir", "Magnúsdóttir", "Pétursson", "Rósa", "Ólafsdóttir", "Kristjánsson", "Sverrisson"],
  "Switzerland": ["Müller", "Schmid", "Bachmann", "Meier", "Hofmann", "Keller", "Fischer", "Weber", "Schneider", "Harris", "Zimmermann", "Schwarz", "Koch", "Jäkel", "Löw", "Gerber", "Ziegler", "Haller", "Bürki", "Rieder", "Hug", "Gross", "Sutter", "Frey", "Gysin"],
  "Austria": ["Müller", "Gruber", "Wagner", "Hofmann", "Huber", "Pichler", "Schmidt", "Maier", "Weber", "Klein", "Schneider", "Linz", "Fuchs", "Koch", "Mayer", "Lechner", "Haas", "Pichler", "Hirsch", "Nieder", "Kral", "Wolf", "Zeller", "Stadler", "Kronberger"],
  "Poland": ["Nowak", "Kowalski", "Wiśniewski", "Wójcik", "Kozłowski", "Jankowski", "Krawczyk", "Zieliński", "Woźniak", "Szymański", "Kruk", "Nowicki", "Mazur", "Kaczmarek", "Bąk", "Sikora", "Chmiel", "Górski", "Duda", "Kubiak", "Sikora", "Wróbel", "Jasiński", "Górska", "Piotrowski"],
  "Czech Republic": ["Novák", "Svoboda", "Novotný", "Dvořák", "Černý", "Procházka", "Kovář", "Růžička", "Čermák", "Pokorný", "Sedláček", "Beneš", "Krejčí", "Kolář", "Šebek", "Zeman", "Němec", "Mach", "Mašek", "Jelínek", "Bláha", "Šimon", "Janda", "Lukáš"],
  "Hungary": ["Kovács", "Szabó", "Tóth", "Nagy", "Kiss", "Molnár", "Varga", "Farkas", "Horváth", "Lukács", "Papp", "Kálmán", "Balázs", "Gulyás", "Németh", "Bognár", "Székely", "Sárközi", "Szűcs", "Siklósi", "Gál", "Kis", "Czucz", "Mészáros", "Dávid"],
  "Romania": ["Popescu", "Ionescu", "Georgescu", "Dumitrescu", "Popa", "Radu", "Marin", "Pascu", "Iliescu", "Munteanu", "Nicolescu", "Matei", "Gheorghe", "Tudor", "Stan", "Vasilescu", "Petrescu", "Oprea", "Andrei", "Dima", "Pop", "Cojocaru", "Sava", "Vlad"],
  "Bulgaria": ["Ivanov", "Georgiev", "Dimov", "Nikolov", "Petrov", "Dimitrov", "Stoyanov", "Kolev", "Vasilev", "Zahariev", "Panchev", "Angelov", "Yankov", "Krastev", "Borisov", "Hristov", "Yordanov", "Kirov", "Ganchev", "Pavlov", "Radev", "Iliev", "Simeonov", "Dinev"],
  "Serbia": ["Jovanović", "Nikolić", "Petrović", "Marković", "Milovanović", "Janković", "Đorđević", "Kostić", "Popović", "Lukić", "Stefanović", "Matić", "Ristić", "Vuković", "Savić", "Tomović", "Rajić", "Mirković", "Gajić", "Vasiljević", "Bojović", "Banjac", "Kolarov", "Pavlović"],
  "Croatia": ["Horvat", "Kovačić", "Novak", "Marić", "Jurić", "Kralj", "Pavić", "Perić", "Tomić", "Vuković", "Galić", "Milić", "Petrak", "Jelić", "Šarić", "Vukman", "Čović", "Šimić", "Tomašević", "Božić", "Vlahović", "Banić", "Prša", "Lukić", "Košić"],
  "Slovakia": ["Kováč", "Novák", "Horváth", "Kubiak", "Škoda", "Varga", "Tóth", "Mikloš", "Kolek", "Pavlík", "Majer", "Križan", "Lukáč", "Černý", "Hlinka", "Zelník", "Konečný", "Straka", "Malík", "Valach", "Kubík", "Rybár", "Rákóczi", "Kollár", "Paška"],
  "Argentina": ["González", "Rodríguez", "García", "Fernández", "López", "Pérez", "Díaz", "Álvarez", "Mendoza", "Martínez", "Moreno", "Ríos", "Castro", "Jiménez", "Ortíz", "Salazar", "Vázquez", "Silva", "Cruz", "Torres", "Gutiérrez", "Morales", "Ramírez", "Vega", "Valdez"],
  "Brazil": ["Silva", "Santos", "Oliveira", "Pereira", "Costa", "Rodrigues", "Almeida", "Sousa", "Nascimento", "Lima", "Gonçalves", "Martins", "Pinto", "Araujo", "Freitas", "Melo", "Carvalho", "Maciel", "Souza", "Barbosa", "Correia", "Nogueira", "Vieira", "Campos", "Dias"],
  "Chile": ["González", "Muñoz", "Pérez", "Fernández", "Sánchez", "Castro", "Silva", "Morales", "Rivas", "Ramos", "Jara", "López", "Bravo", "Navarro", "Mendoza", "Alvarado", "Zúñiga", "Riquelme", "Contreras", "Paredes", "Reyes", "Ortiz", "Vásquez", "Bermúdez", "Tapia"],
  "Colombia": ["García", "Martínez", "Rodríguez", "Hernández", "Gómez", "Castro", "Moreno", "Jaramillo", "Pérez", "Sánchez", "Díaz", "Ramírez", "Ríos", "Mendoza", "Gutiérrez", "Salazar", "Vargas", "Torres", "Reyes", "Valencia", "Arias", "Bermúdez", "Cruz", "Núñez", "Márquez"],
  "Peru": ["García", "Rodríguez", "Fernández", "González", "Pérez", "Martínez", "Muñoz", "Álvarez", "Hernández", "Cruz", "Mendoza", "Silva", "Castro", "Reyes", "Vásquez", "Morales", "Sánchez", "Salazar", "Torres", "Rivas", "Valencia", "Ramos", "Jara", "Bravo", "Chávez"],
  "Venezuela": ["González", "Rodríguez", "Pérez", "García", "Martínez", "Hernández", "Torres", "Sánchez", "Morales", "Castro", "Gómez", "Mendoza", "Reyes", "Ramos", "Salazar", "Silva", "Vásquez", "Ramírez", "Cruz", "Díaz", "Jaramillo", "Alvarado", "Figueroa", "Bravo", "Márquez"],
  "Ecuador": ["González", "Rodríguez", "Pérez", "García", "Fernández", "Morales", "Martínez", "Sánchez", "Reyes", "Alvarado", "Silva", "Torres", "Gómez", "Cruz", "Jaramillo", "Mendoza", "Ramos", "Vásquez", "Ramírez", "Castro", "Valencia", "Bravo", "Díaz", "Muñoz", "Sánchez"],
  "Uruguay": ["González", "Rodríguez", "Fernández", "Pérez", "García", "Martínez", "Silva", "Morales", "Sánchez", "Gómez", "Castro", "Mendoza", "Torres", "Reyes", "Ríos", "Vázquez", "Díaz", "Muñoz", "Ramírez", "Gutiérrez", "Bravo", "Vega", "Alonso", "Valdés", "García"],
  "Bolivia": ["García", "Martínez", "Pérez", "González", "Rodríguez", "Morales", "Fernández", "Torres", "Silva", "Gómez", "Castro", "Mendoza", "Sánchez", "Reyes", "Ramírez", "Cruz", "Vásquez", "Jara", "Alvarado", "Rivas", "Bravo", "Soria", "Valencia", "Jaramillo", "Núñez"],
  "Paraguay": ["González", "Rodríguez", "Pérez", "Martínez", "Fernández", "Silva", "Gómez", "Morales", "Castro", "Sánchez", "Reyes", "Torres", "Mendoza", "Rivas", "Cruz", "Valdez", "Jara", "Vásquez", "Ramírez", "Bravo", "Muñoz", "Díaz", "Alvarado", "Vega", "Cruz"],
  "Guyana": ["Mohamed", "Persaud", "Singh", "Ali", "Ramkissoon", "Khan", "Jagdeo", "Narine", "Lall", "Hosein", "Gordon", "Noble", "Ramsay", "Bhagat", "Deo", "Ameer", "Sookram", "Omar", "Yadav", "Bissoon", "Reddy", "Paul", "Ali", "Sharma", "Williams"],
  "Suriname": ["Jansen", "Koeiman", "Schenk", "Alibux", "Loez", "Ramdharie", "Kumar", "Ali", "Aboe", "Jagroep", "Naar", "Hira", "Sookram", "Jankie", "Nisha", "Sanoe", "Ramkhelawan", "Khan", "Ramnarine", "Dewnarain", "Naar", "Jalah", "Hoost", "Sampson", "Sutaran"],
  "French Guiana": ["Lima", "Da Silva", "Roche", "Bertrand", "Benoît", "Charles", "Leblanc", "Gauthier", "Mercier", "Dumont", "Pichon", "Durand", "Laurent", "Gros", "Delmas", "Fournier", "Dufresne", "Philippe", "Houdard", "Vidal", "Laurent", "Chevalier", "Dufour", "Deschamps", "Valentin"],
  "Nigeria": ["Abubakar", "Ogunleye", "Adams", "Ojo", "Aliyu", "Ibrahim", "Akinbiyi", "Okoro", "Abiola", "Bello", "Nwankwo", "Eze", "Sani", "Umar", "Okafor", "Ibrahim", "Adebayo", "Mohammed", "Ali", "Jibril", "Oluwaseun", "Olawale", "Afolabi", "Ogunyemi", "Ogunjobi"],
  "South Africa": ["Nkosi", "Mkhize", "Khumalo", "Modise", "Dlamini", "Moyo", "Ndlovu", "Mthembu", "Zuma", "Petersen", "Makgoba", "Mabena", "Molefe", "Radebe", "Msimango", "Kekana", "Mashaba", "Mabasa", "Langa", "Gumede", "Ramoshaba", "Hadebe", "Mabasa", "Molefe", "Makhathini"],
  "Kenya": ["Kimani", "Mwangi", "Ochieng", "Otieno", "Karanja", "Wangui", "Njuguna", "Kibaki", "Muriuki", "Achieng", "Mutua", "Ndegwa", "Muthoni", "Kibet", "Wambui", "Chege", "Kilonzo", "Ndungu", "Mbugua", "Karanja", "Njeri", "Maina", "Mugo", "Mutunga", "Kamau"],
  "Ghana": ["Owusu", "Addo", "Ankrah", "Amoako", "Asante", "Boateng", "Bempah", "Mensah", "Osei", "Akuffo", "Nketiah", "Kwarteng", "Gyasi", "Nana", "Quartey", "Yeboah", "Asiedu", "Kusi", "Appiah", "Ofori", "Agyei", "Kofi", "Ofori", "Kwarteng", "Nyarko"],
  "Ethiopia": ["Mohammed", "Abebe", "Tadesse", "Fikre", "Kebede", "Mulu", "Hailu", "Ayele", "Bekele", "Tewodros", "Tefera", "Mekonnen", "Mesfin", "Asfaw", "Amsalu", "Girma", "Biruk", "Mekdes", "Wondimu", "Biruk", "Beyene", "Hanna", "Gashaw", "Kassahun", "Mihret"],
  "Uganda": ["Kato", "Kigongo", "Mugisha", "Nabirye", "Nsubuga", "Ssekajja", "Nabweru", "Nambooze", "Kibirige", "Mukiibi", "Kisakye", "Twebaze", "Mugisha", "Kagaba", "Namirembe", "Mugisha", "Mwesigwa", "Katuramu", "Ssentongo", "Kasumba", "Muwonge", "Basaal", "Bukenya", "Kizito", "Mugisha"],
  "Tanzania": ["Mwanza", "Mwangangi", "Chacha", "Kilimanjaro", "Mnyuka", "Ndesambure", "Doss", "Sikombe", "Kibamba", "Nkwabi", "Mwakapanga", "Mamboleo", "Jafari", "Ng'oma", "Mcha", "Mwezi", "Kalanga", "Mujuni", "Mumba", "Kibanda", "Katana", "Nabii", "Babu", "Ndembe", "Karimu"],
  "Zimbabwe": ["Moyo", "Chirau", "Dube", "Maseko", "Ncube", "Makoni", "Mabika", "Gumbo", "Nyathi", "Mhlanga", "Zenda", "Dhlamini", "Nkomo", "Zhou", "Mlambo", "Sibanda", "Gatsheni", "Mabika", "Chikanya", "Mugabe", "Gutu", "Muswere", "Sibanda", "Mapfumo", "Nkomo"],
  "Rwanda": ["Nkurunziza", "Bizimana", "Munyaneza", "Niyonzima", "Ndayisaba", "Munyankindi", "Hakizimana", "Mugisha", "Mukamana", "Nkurunziza", "Kamanzi", "Mugiraneza", "Uwimana", "Uwase", "Ntakirutimana", "Rukundo", "Habyarimana", "Mucyo", "Mukeshimana", "Ishimwe", "Nshuti", "Kabera", "Ndiaye", "Munyakazi"],
  "Burundi": ["Nkurunziza", "Ndayishimiye", "Habimana", "Munyaneza", "Niyonkuru", "Bizimana", "Munyaneza", "Ndagijimana", "Habarugira", "Muriungi", "Habyarimana", "Mukandori", "Ndikumana", "Niyonzima", "Rukundo", "Munyankindi", "Nishimwe", "Ndiaye", "Niyigena", "Munyakazi", "Hakizimana", "Nkurunziza", "Nshimiyimana", "Ishimwe"],
  "Somalia": ["Mohamed", "Ali", "Ahmed", "Hassan", "Abdi", "Mohamud", "Ismail", "Yusuf", "Hassan", "Mubarak", "Farah", "Abdiqadir", "Mohamed", "Mohamud", "Abdullahi", "Amin", "Dahir", "Mohamoud", "Fadumo", "Nur", "Adan", "Ibrahim", "Mohamud", "Mohamed", "Hussein"],
  "South Sudan": ["Omar", "Abdullah", "Hassan", "Ali", "Mohamed", "Yusuf", "Ibrahim", "Ahmed", "Salim", "Adan", "Mohamud", "Musa", "Nimir", "Khalid", "Mohammed", "Omar", "Amin", "Mokhtar", "Hamid", "Yassin", "Elmi", "Mohammed", "Abdi", "Ali", "Hussein"],
  "Central African Republic": ["Kossi", "Yao", "Kouadio", "Kouame", "Fadiga", "Doumbia", "Konan", "Koné", "Yapo", "Ouatara", "Kafando", "Tano", "Ouattara", "N'Guessan", "Kouadio", "Yao", "Zokou", "Koffi", "Yao", "Koné", "Koffi", "Bamba", "Diby", "Zahui", "Zekpédé"],
  "Ivory Coast": ["Kouadio", "Yao", "Koffi", "Kouame", "N'Guessan", "Koné", "Yapi", "Fadiga", "Doumbia", "Bamba", "Ouattara", "Kaba", "Yao", "Diomandé", "Kouadio", "Soro", "Zoukou", "Yapo", "Koffi", "Diby", "Bamba", "N'Guessan", "Koffi", "Soro", "Fofana"],
  "Gabon": ["Nzeng", "Nguema", "Ongong", "Obiang", "Nguema", "Koumba", "Mebey", "Bongo", "Nzingha", "Ona", "Ngoma", "Moukou", "Ibang", "Ngoma", "Nze", "Koumba", "Nguema", "Ngouma", "Mebey", "Moukou", "Moukou", "Makaya", "Eteki", "Mombo", "Moussavou"],
  "Equatorial Guinea": ["Nguema", "Ongong", "Obiang", "Esono", "Mbeng", "Mba", "Ndong", "Kikang", "Meko", "Moussavou", "Nguema", "Obiang", "Mocach", "Dibang", "Nchama", "Mba", "Moko", "Boma", "Eteki", "Mombo", "Asebo", "Ngon", "Mokogo", "Nzasu", "Mole"],
  "Sierra Leone": ["Kamara", "Koroma", "Bangura", "Sesay", "Fofanah", "Jalloh", "Tajudeen", "Kallon", "Mansaray", "Keita", "Jalloh", "Abdullah", "Sengbeh", "Conteh", "Kamara", "Fofanah", "Banya", "Bangura", "Sesay", "Kanu", "Sosseh", "Jalloh", "Kanu", "Fofana", "Turay"],
  "Liberia": ["Johnson", "Williams", "Brown", "Smith", "Jones", "Cooper", "Roberts", "Miller", "Taylor", "King", "Coleman", "Moore", "Baker", "Anderson", "Lewis", "Scott", "Gray", "Hill", "Wright", "Harris", "Martin", "White", "Harris", "Thomas", "Jackson"],
  "Mauritius": ["Odin", "Teeluck", "Gooriah", "Sookun", "Sewraj", "Chung", "Odin", "Yoon", "Gungaram", "Keen", "Yusuf", "Sewraj", "Pillay", "Chung", "Boolell", "Gobin", "Sookun", "Aden", "Hossen", "Kumar", "Odin", "Singh", "Goh", "Gungaram"],
  "Malawi": ["Chirwa", "Phiri", "Moyo", "Kaunda", "Kanyama", "Kambalame", "Manda", "Chimwaza", "Nyirenda", "Nkhoma", "Mbuya", "Chikuni", "Tembo", "Kachindamoto", "Chipeta", "Banda", "Kaunda", "Muliya", "Kalilani", "Kang'oma", "Kande", "Jere", "Chitsulo", "Nkhoma"],
  "Egypt": ["Mohamed", "Ahmed", "Hassan", "Ali", "Ibrahim", "Abdel", "Mohsen", "Farag", "Hussein", "Abdelrahman", "Gaber", "El-Sayed", "Moussa", "El-Kholy", "El-Masry", "Fathy", "Khaled", "Sayed", "Mahmoud", "Omar", "Ali", "Sami", "Tawfik", "Gaber", "Hegazy"],
  "Morocco": ["El Fassi", "Benkirane", "El Idrissi", "Ait Benhaddou", "Moussaoui", "Boulahya", "Ouarzazi", "Cherradi", "Lahbabi", "Belkacem", "El Khayati", "Ouali", "El Kaddouri", "Lahlimi", "Kharbouch", "Lahlou", "El Mzouri", "El Gharbi", "Bourouba", "Rachidi", "El Aouad", "El Mokhtari", "Zeroual", "Yazid", "El Omari"],
  "Algeria": ["Benhamou", "Khaled", "Amar", "Benguedoud", "Bouchetata", "Ali", "Mechri", "Bensalem", "Moussaoui", "Boudaoud", "Haddad", "Benmohamed", "Mebarki", "Guedira", "Lazaar", "Touati", "Khelil", "Khalfi", "Medjadji", "Cherif", "Boudiaf", "Abbas", "Benjelloun", "Chikhi", "Mouhoub"],
  "Tunisia": ["Ben Ali", "Jemaa", "Boudiaf", "Hamdi", "Maaloul", "Gharbi", "Ben Ammar", "Mouelhi", "Zitouni", "Khemiri", "Rached", "Khalil", "Mnasri", "Fadli", "Sassi", "Khalifa", "Hajji", "Ghediri", "Khammari", "Bounoua", "Jemaa", "Ouni", "Mechri", "Khemiri", "Abid"],
  "Libya": ["El-Sayed", "Mohamed", "Ali", "Gaddafi", "Abdallah", "Othman", "Zaid", "Moussa", "El-Beshir", "Mokhtar", "Al-Sadek", "Ghanem", "Abu Shnaf", "Mohamed", "El-Masri", "El-Masri", "Ahmed", "El-Khalil", "Mokhtar", "Nassib", "Zaid", "Tariq", "Ghadir", "Farag", "El-Khabir"],
  "Mauritania": ["Ould", "Baba", "Ould Mohamed", "Ould Ahmed", "Ould Cheikh", "Ould Abdi", "Ould Mahmoud", "Ould Salem", "Ould Sidna", "Ould Bocar", "Ould Ahmed", "Ould Bouh", "Ould Mohamed", "Ould Sidi", "Ould Nasser", "Ould Babou", "Ould Moussa", "Ould Ali", "Ould Said", "Ould Mohamed", "Ould Ly", "Ould Said", "Ould Mohamed", "Ould Bocar", "Ould Sidi"],
  "Western Sahara": ["El-Lahbib", "Bouhali", "Jemaâ", "Said", "El-Ghazali", "Mohamed", "El-Ouali", "Ahmed", "El-Hassani", "Bey", "Ould", "Mohamed", "Mhamed", "Salem", "Bouchiha", "Brahim", "El-Hassani", "El-Ayadi", "El-Ghazali", "Mohamed", "Mhamed", "Ahmed", "Salem", "Bouhali", "Brahim"],
  "Sudan": ["Mohamed", "Ahmed", "Ali", "Hassan", "Ibrahim", "Abdallah", "El-Tayeb", "El-Nour", "Abdelrahman", "Moussa", "Omer", "Nour", "Salih", "Osman", "Abu Bakr", "Ali", "Bashir", "Ishaq", "Gafar", "Ahmed", "Bashir", "Abdullahi", "El-Tayeb", "Khalil", "Mohamed"],
  "USA": ["Smith", "Johnson", "Williams", "Jones", "Brown", "Davis", "Miller", "Wilson", "Moore", "Taylor", "Anderson", "Thomas", "Jackson", "White", "Harris", "Martin", "Thompson", "Garcia", "Martinez", "Robinson", "Clark", "Rodriguez", "Lewis", "Lee", "Walker"],
  "Israel": ["Cohen", "Levi", "Mizrahi", "Peretz", "Ben-David", "Shapiro", "Katz", "Goldstein", "Azulai", "Friedman", "Segal", "Golan", "Rosen", "Edelstein", "Sharon", "Weiss", "Greenberg", "Barak", "Halevy", "Shaked", "Hoffman", "Israeli", "Rivlin", "Stern", "Amsalem"],
  "China": ["Wang", "Li", "Zhang", "Liu", "Chen", "Yang", "Huang", "Zhao", "Wu", "Zhou", "Xu", "Sun", "Ma", "Guo", "Lin", "He", "Liao", "Luo", "Peng", "Jiang", "Xie", "Hsu", "Deng", "Cai", "Yuan"],
  "India": ["Singh", "Kumar", "Sharma", "Patel", "Gupta", "Mishra", "Reddy", "Chopra", "Shah", "Das", "Mehta", "Jain", "Arora", "Kaur", "Yadav", "Nair", "Iyer", "Raj", "Chaudhary", "Rao", "Ghosh", "Agarwal", "Singh", "Joshi", "Khan"],
  "Japan": ["Sato", "Suzuki", "Takahashi", "Tanaka", "Yamamoto", "Kobayashi", "Matsumoto", "Inoue", "Ishikawa", "Kaneko", "Saito", "Kato", "Yoshida", "Kondo", "Yamada", "Fujimoto", "Nakamura", "Arai", "Yoshida", "Hasegawa", "Kawasaki", "Ono", "Watanabe", "Miyazaki"],
  "South Korea": ["Kim", "Lee", "Park", "Jeong", "Choi", "Cho", "Yoon", "Im", "Lim", "Kang", "Jang", "Oh", "Hwang", "Ahn", "Joo", "Son", "Yoon", "Shin", "Ryu", "Yoo", "Kim", "Jung", "Han", "Seo", "Na"],
  "Vietnam": ["Nguyen", "Tran", "Le", "Pham", "Huynh", "Hoang", "Nguyen", "Bui", "Do", "Duong", "Vo", "Ngo", "Truong", "Phan", "Dinh", "Le", "Ho", "Ngoc", "Tuan", "Nguyen", "Pham", "Hanh", "Ha", "Dong", "Lam"],
  "Thailand": ["Nguyen", "Pong", "Chai", "Suk", "Pong", "Kong", "Bun", "Sang", "Chai", "Nok", "Som", "Tung", "Ming", "Mong", "Chai", "Pao", "Rung", "Kao", "Yung", "Dai", "Yao", "Wang", "Mai", "Chiu", "Lin"],
  "Malaysia": ["Ahmad", "Lee", "Tan", "Abdullah", "Mohamad", "Ng", "Cheong", "Lai", "Yap", "Lim", "Chong", "Ong", "Liew", "Koh", "Teoh", "Zainal", "Khan", "Mohd", "Jamil", "Aziz", "Chong", "Kumar", "Goh", "Rahman"],
  "Singapore": ["Tan", "Ng", "Lim", "Lee", "Chong", "Goh", "Tan", "Ong", "Yeo", "Ho", "Ng", "Zhang", "Wong", "Teo", "Soh", "Koh", "Lai", "Sim", "Chua", "Yeo", "Quek", "Sim", "Liu", "Goh"],
  "Indonesia": ["Sutrisno", "Wijaya", "Putra", "Sari", "Yuliana", "Hadi", "Nur", "Sari", "Hutagalung", "Prasetyo", "Hadi", "Susanto", "Wahyudi", "Gunawan", "Indra", "Nugroho", "Lestari", "Yani", "Lestari", "Sudarsono", "Kusuma", "Fadli", "Arief", "Purnama"],
  "Philippines": ["Santos", "Reyes", "Cruz", "Gonzalez", "Delgado", "Torres", "Garcia", "Rodriguez", "Martinez", "Rivera", "Flores", "Diaz", "Bautista", "Vasquez", "Mendoza", "Castro", "Ramos", "Santos", "Cruz", "Gomez", "Alvarez", "Pineda", "Mendoza", "Dela Cruz"],
  "Saudi Arabia": ["Al-Farhan", "Al-Harbi", "Al-Mutairi", "Al-Saud", "Al-Qahtani", "Al-Otaibi", "Al-Johani", "Al-Ghamdi", "Al-Shammari", "Al-Dosari", "Al-Harbi", "Al-Shehri", "Al-Mansour", "Al-Muhaidib", "Al-Hassan", "Al-Salman", "Al-Nasser", "Al-Rashid", "Al-Khalid", "Al-Muqbel", "Al-Sulaiman", "Al-Jabri", "Al-Hamdan", "Al-Zahrani", "Al-Subaie"],
  "United Arab Emirates": ["Al-Nahyan", "Al-Maktoum", "Al-Qasimi", "Al-Buainain", "Al-Ali", "Al-Khalifa", "Al-Hamadi", "Al-Raisi", "Al-Mansoori", "Al-Sheikh", "Al-Hosani", "Al-Kaabi", "Al-Hammadi", "Al-Jaberi", "Al-Mazrouei", "Al-Dhaheri", "Al-Suwaidi", "Al-Jarwan", "Al-Hamiri", "Al-Khater", "Al-Suwaidi", "Al-Yafei", "Al-Balushi", "Al-Bastaki", "Al-Mutawa"],
  "Qatar": ["Al-Thani", "Al-Khalifa", "Al-Muraikhi", "Al-Jaber", "Al-Saadi", "Al-Attiyah", "Al-Kuwari", "Al-Naimi", "Al-Suwaidi", "Al-Mansoori", "Al-Dosari", "Al-Hajri", "Al-Sabah", "Al-Mansoor", "Al-Sharif", "Al-Hamadi", "Al-Khater", "Al-Saadi", "Al-Ali", "Al-Rumaihi", "Al-Ghanim", "Al-Mughairy", "Al-Jaber", "Al-Kubaisi", "Al-Maadeed"],
  "Kuwait": ["Al-Sabah", "Al-Hamad", "Al-Khaled", "Al-Awadhi", "Al-Mutairi", "Al-Omari", "Al-Khulaifi", "Al-Jarallah", "Al-Ali", "Al-Daihani", "Al-Muzaini", "Al-Fadhli", "Al-Rashed", "Al-Sayer", "Al-Husaini", "Al-Yaseen", "Al-Sayegh", "Al-Qattan", "Al-Muhanna", "Al-Muhsin", "Al-Khater", "Al-Rashid", "Al-Farhan", "Al-Bedah", "Al-Qurashi"],
  "Oman": ["Al-Said", "Al-Harthy", "Al-Khuleifi", "Al-Mandhari", "Al-Saidi", "Al-Habsi", "Al-Balushi", "Al-Azri", "Al-Mansoori", "Al-Jabri", "Al-Maqbali", "Al-Hadi", "Al-Kalbani", "Al-Rahbi", "Al-Khalili", "Al-Mamari", "Al-Rashdi", "Al-Ghamdi", "Al-Hinai", "Al-Awadhi", "Al-Hashmi", "Al-Rahbi", "Al-Muqbil", "Al-Hamdi", "Al-Sharqi"],
  "Jordan": ["Al-Majali", "Al-Khader", "Al-Sheikh", "Al-Tarawneh", "Al-Habash", "Al-Khawaldeh", "Al-Sarayra", "Al-Zu'bi", "Al-Mamlouk", "Al-Tarawneh", "Al-Nsour", "Al-Jarrah", "Al-Qader", "Al-Hawamdeh", "Al-Fayez", "Al-Khaled", "Al-Abbadi", "Al-Tarawneh", "Al-Hussein", "Al-Jbawi", "Al-Qader", "Al-Damour", "Al-Ali", "Al-Jarrah", "Al-Soud"],
  "Lebanon": ["Khalil", "Jaber", "Hassan", "Fares", "Hariri", "Nassif", "Sabbagh", "Said", "Khalaf", "Saliba", "Mouawad", "Barakat", "El-Haddad", "Zein", "Farhat", "Abou Rached", "Haddad", "Sleiman", "Boulos", "Mikati", "Shihab", "Khoury", "Rami", "Joubran", "El-Amin"],
  "Syria": ["Al-Assad", "Al-Mohammad", "Al-Sayed", "Al-Haddad", "Al-Ali", "Al-Khalil", "Al-Hussein", "Al-Daher", "Al-Mustafa", "Al-Jarrah", "Al-Sarraf", "Al-Zein", "Al-Nasser", "Al-Qader", "Al-Khouri", "Al-Malki", "Al-Abdullah", "Al-Mohammed", "Al-Rashid", "Al-Jaafar", "Al-Ma'arouf", "Al-Sharif", "Al-Shaaban", "Al-Khalifa", "Al-Raouf"],
  "Iraq": ["Al-Sadr", "Al-Maliki", "Al-Jabouri", "Al-Tamimi", "Al-Hakim", "Al-Kadhim", "Al-Khuzai", "Al-Saadi", "Al-Hashemi", "Al-Mahdi", "Al-Dulaimi", "Al-Jabari", "Al-Talib", "Al-Khalaf", "Al-Rashid", "Al-Ani", "Al-Hamdi", "Al-Farisi", "Al-Qaisi", "Al-Mansoor", "Al-Najafi", "Al-Ali", "Al-Zubaidi", "Al-Jassem", "Al-Azzawi"],
  "Bahrain": ["Al-Khalifa", "Al-Bahrani", "Al-Maliki", "Al-Mansoor", "Al-Jowder", "Al-Saidi", "Al-Buainain", "Al-Haddad", "Al-Rumaihi", "Al-Sheikh", "Al-Kooheji", "Al-Hamadi", "Al-Balushi", "Al-Muqbil", "Al-Ali", "Al-Mahmood", "Al-Hamoud", "Al-Qadheeb", "Al-Khulaifi", "Al-Karbi", "Al-Tarazi", "Al-Sayed", "Al-Jabri", "Al-Muhaidib", "Al-Siddiq"],
  "Yemen": ["Al-Hadi", "Al-Sabri", "Al-Saeed", "Al-Mutairi", "Al-Khatib", "Al-Qadhi", "Al-Mujahid", "Al-Mansoori", "Al-Mekhlafi", "Al-Nahari", "Al-Harithi", "Al-Shaibi", "Al-Muaini", "Al-Qubati", "Al-Mashaari", "Al-Hamdi", "Al-Jabri", "Al-Jawfi", "Al-Nassir", "Al-Rahman", "Al-Ahmad", "Al-Khaled", "Al-Jibreen", "Al-Hariri", "Al-Rimi"],
  "Iran": ["Mohammadi", "Ahmadi", "Hosseini", "Karami", "Rezaei", "Jafari", "Mousavi", "Hashemi", "Zarei", "Nasiri", "Rahimi", "Azimi", "Ghaffari", "Shahbazi", "Farahani", "Sadeghi", "Tavakoli", "Nasseri", "Moghaddam", "Gholami", "Kiani", "Seyed", "Ebrahimi", "Yazdani", "Fadaei"],
  "Australia": ["Smith", "Johnson", "Williams", "Brown", "Jones", "Miller", "Davis", "Wilson", "Moore", "Taylor", "Anderson", "Thomas", "Jackson", "White", "Harris", "Martin", "Thompson", "Garcia", "Martinez", "Robinson", "Clark", "Rodriguez", "Lewis", "Walker", "Hall"],
  "New Zealand": ["Smith", "Jones", "Williams", "Brown", "Taylor", "Wilson", "Martin", "Thompson", "Robinson", "Anderson", "Lee", "Nguyen", "Johnson", "Ng", "Campbell", "Miller", "Walker", "O'Connor", "Sullivan", "Harris", "Davis", "Clark", "Mitchell", "Walker"],
  "Canada": ["Smith", "Johnson", "Williams", "Brown", "Jones", "Tremblay", "Gagnon", "Martin", "Fortin", "Bouchard", "Roy", "Gauthier", "Thibault", "Lavoie", "Côté", "Leblanc", "Lefebvre", "Lemoine", "Dube", "Ouellet", "Pelletier", "Carrier", "Blais", "Bergeron", "Bérubé"],
  "Mexico": ["Hernandez", "Garcia", "Martinez", "Lopez", "Gonzalez", "Rodriguez", "Perez", "Sanchez", "Ramirez", "Flores", "Garza", "Morales", "Cruz", "Reyes", "Ortiz", "Guzman", "Vasquez", "Rios", "Mendoza", "Castro", "Serrano", "Pineda", "Jimenez", "Bravo", "Rivera"],
  "Guatemala": ["García", "Mendoza", "Lopez", "Martínez", "Morales", "Sánchez", "Castro", "Ruiz", "Flores", "Jiménez", "Ramos", "Pérez", "Alvarado", "Vásquez", "Ordoñez", "González", "Escobar", "Cruz", "Reyes", "Arévalo", "Hernández", "Salazar", "Solis", "Serrano", "Velásquez"],
  "Costa Rica": ["Rodriguez", "Gonzalez", "Martínez", "Hernández", "Jiménez", "Lopez", "García", "Vargas", "Morales", "Castro", "Chaves", "Alvarado", "Sánchez", "Pérez", "Ruiz", "Serrano", "Rojas", "Quesada", "Salazar", "Mora", "Araya", "Jiménez", "Pinto", "Gómez", "Cordero"],

};

export const popularFirstNames: { [country: string]: string[] } = {
  "Germany": ["Luca", "Emma", "Noah", "Hannah", "Leon", "Sophia", "Paul", "Mia", "Elias", "Anna", "Felix", "Lea", "Max", "Marie", "Liam", "Sophie", "Jakob", "Ella", "Alexander", "Lina", "Ben", "Charlotte", "Oskar", "Lara", "Louis"],
  "France": ["Liam", "Emma", "Lucas", "Chloé", "Gabriel", "Lina", "Jules", "Manon", "Arthur", "Lou", "Louis", "Jade", "Ethan", "Alice", "Paul", "Zoe", "Adam", "Léa", "Noah", "Camille", "Gaspard", "Inès", "Milo", "Sarah", "Hugo"],
  "Italy": ["Leonardo", "Sofia", "Giuseppe", "Aurora", "Giovanni", "Ginevra", "Antonio", "Emma", "Matteo", "Alice", "Alessandro", "Greta", "Lorenzo", "Livia", "Andrea", "Martina", "Francesco", "Chiara", "Filippo", "Sara", "Riccardo", "Beatrice", "Edoardo", "Valentina", "Tommaso"],
  "Spain": ["Hugo", "Sofía", "Martín", "Lucía", "Lucas", "Valeria", "Mateo", "Camila", "Alejandro", "Mía", "Daniel", "María", "Pablo", "Julia", "Álvaro", "Carla", "Adrián", "Paula", "José", "Nerea", "David", "Irene", "Jorge", "Ana", "Rafael"],
  "United Kingdom": ["Olivia", "George", "Isla", "Noah", "Ava", "Arthur", "Sophia", "Jack", "Emily", "Harry", "Lily", "Thomas", "Mia", "James", "Amelia", "William", "Ella", "Benjamin", "Isabella", "Lucas", "Charlotte", "Henry", "Harper", "Alexander", "Grace"],
  "Portugal": ["Maria", "João", "Ana", "Pedro", "Beatriz", "Miguel", "Leonor", "Francisco", "Matilde", "Rui", "Sofia", "Gonçalo", "Diana", "Gabriel", "Carla", "Ricardo", "Laura", "Tiago", "Inês", "José", "Clara", "Bruno", "Catarina", "Paulo", "Lúcia"],
  "Netherlands": ["Emma", "Noah", "Julia", "Liam", "Sophie", "Milan", "Zoë", "Lucas", "Lotte", "Finn", "Eva", "Daan", "Anna", "Tess", "Joris", "Nina", "Hugo", "Sara", "Mees", "Olivia", "Bram", "Luna", "Max", "Mara", "Eline"],
  "Belgium": ["Emma", "Noah", "Olivia", "Liam", "Sofia", "Lucas", "Ava", "Milan", "Lotte", "Hugo", "Ella", "Arthur", "Julien", "Clara", "Louis", "Marie", "Alexander", "Tess", "Gabriel", "Sarah", "Tom", "Nina", "Lena", "Maya", "Ethan"],
  "Sweden": ["Alice", "Liam", "Maja", "Noah", "Ella", "William", "Olivia", "Hugo", "Astrid", "Lucas", "Ida", "Oskar", "Emma", "Vera", "Elias", "Freja", "Leon", "Sofia", "Wilhelm", "Liv", "Hannah", "Axel", "Elin", "Nils", "Klara"],
  "Norway": ["Jakob", "Sofie", "Emil", "Nora", "Odin", "Ella", "Magnus", "Anna", "Aksel", "Liv", "Lukas", "Frida", "Sander", "Ida", "Felix", "Maja", "Mikkel", "Siri", "Isak", "Aurora", "Henrik", "Selma", "Mia", "Elias", "Mathilde"],
  "Denmark": ["William", "Emma", "Noah", "Sofie", "Oliver", "Freja", "Lucas", "Anna", "Mikkel", "Ida", "Oscar", "Nanna", "Carl", "Karla", "Sebastian", "Mia", "Valdemar", "Alma", "Malthe", "Signe", "Jakob", "Ellen", "Aksel", "Sofie", "Lukas"],
  "Finland": ["Leo", "Sofia", "Oskari", "Ella", "Elias", "Aino", "Onni", "Emma", "Leo", "Olivia", "Miko", "Aurora", "Matti", "Lotta", "Lukas", "Inka", "Jesse", "Hanna", "Aaro", "Kaisa", "Mikko", "Elina", "Roni", "Jenna", "Joni"],
  "Iceland": ["Jón", "Guðrún", "Ólafur", "Anna", "Jóhann", "Sigríður", "Bjarni", "Eva", "Magnús", "Ragnheiður", "Sigurður", "Svala", "Haukur", "Elín", "Arnar", "Rósa", "Þórður", "Hildur", "Karl", "Hanna", "Pétur", "Sólveig", "Stefán", "Guðbjörg", "Einar"],
  "Switzerland": ["Liam", "Emma", "Noah", "Sophie", "Gabriel", "Lina", "Leon", "Mia", "Elena", "Paul", "Sarah", "Julian", "Sofia", "Max", "Laura", "Hugo", "Mia", "Tom", "Nina", "Emilie", "Oscar", "Luca", "Isabelle", "Jules", "Alice"],
  "Austria": ["Paul", "Anna", "Max", "Emma", "Lukas", "Mia", "Leon", "Sophie", "Felix", "Hannah", "Jakob", "Lena", "Tim", "Sarah", "David", "Marie", "Nina", "Tom", "Laura", "Matthias", "Julia", "Niklas", "Lisa", "Jonas", "Ella"],
  "Poland": ["Antoni", "Maria", "Jakub", "Anna", "Jan", "Katarzyna", "Szymon", "Zuzanna", "Stanisław", "Julia", "Michał", "Agnieszka", "Krzysztof", "Aleksandra", "Paweł", "Monika", "Adam", "Natalia", "Łukasz", "Ewa", "Tomasz", "Joanna", "Grzegorz", "Martyna", "Andrzej"],
  "Czech Republic": ["Jakub", "Eliška", "Tomáš", "Anna", "Ondřej", "Tereza", "Petr", "Sofie", "Martin", "Nela", "Vojtěch", "Kristýna", "Jan", "Veronika", "Marek", "Jana", "David", "Lucie", "Michal", "Zuzana", "Lukáš", "Eva", "Jaroslav", "Monika", "Filip"],
  "Hungary": ["Luca", "László", "Katalin", "Gábor", "Eszter", "Márton", "Anna", "Bence", "Zsófia", "Miklós", "Krisztina", "József", "Réka", "Péter", "Viktória", "Judit", "Ferenc", "Klara", "Sándor", "Lili", "Mária", "Zoltán", "Adél", "Imre", "Lóránt"],
  "Romania": ["Andrei", "Maria", "Gabriel", "Elena", "Ion", "Ioana", "Mihai", "Ana", "Vasile", "Laura", "Radu", "Alexandra", "Nicolae", "Monica", "Dorian", "Cristina", "George", "Irina", "Daniel", "Simona", "Stefan", "Larisa", "Florin", "Adriana", "Marius"],
  "Bulgaria": ["Ivan", "Maria", "Georgi", "Elena", "Dimitar", "Nina", "Petar", "Vesela", "Mihail", "Radka", "Yordan", "Svetlana", "Nikolay", "Tsvetelina", "Kiril", "Radoslava", "Plamen", "Irina", "Hristo", "Maya", "Boris", "Yulia", "Stoyan", "Milen", "Zdravko"],
  "Serbia": ["Nikola", "Jovana", "Marko", "Ana", "Stefan", "Milica", "Aleksandar", "Ivana", "Nemanja", "Marija", "Vuk", "Dragana", "Aleksandra", "Milan", "Katarina", "Luka", "Nina", "Dusan", "Jelena", "Rade", "Sonja", "Bojan", "Tijana", "Zoran", "Sara"],
  "Croatia": ["Luka", "Marija", "Ivan", "Ana", "Marko", "Ivana", "Petar", "Katarina", "Josip", "Maja", "Tomislav", "Nina", "Dario", "Kristina", "Ante", "Lucija", "Mislav", "Iva", "Damir", "Renata", "Viktor", "Tanja", "Filip", "Lana", "Mario"],
  "Slovakia": ["Jakub", "Anna", "Martin", "Eva", "Peter", "Mária", "Tomáš", "Lucia", "Marek", "Jana", "Juraj", "Zuzana", "Pavol", "Veronika", "Michal", "Tatiana", "Róbert", "Michaela", "Richard", "Monika", "Daniel", "Barbora", "Lukáš", "Jozef", "Ivana"],
  "Argentina": ["Mateo", "Sofía", "Benjamín", "Isabella", "Matías", "Valentina", "Lucas", "María", "Agustín", "Juana", "Tomas", "Camila", "Juan", "Mía", "Santiago", "Lucía", "Sebastián", "Renata", "Nicolás", "Victoria", "Emilia", "Tomás", "Gabriela", "Diego", "Florencia"],
  "Brazil": ["Miguel", "Isabella", "Arthur", "Sophia", "Heitor", "Valentina", "Gabriel", "Luiza", "Pedro", "Alice", "Joaquim", "Laura", "Bernardo", "Manuela", "Matheus", "Olivia", "Rafael", "Ana", "Guilherme", "Lívia", "Felipe", "Mariana", "Davi", "Emanuelle", "Heloísa"],
  "Chile": ["Mateo", "Isabella", "Santiago", "Camila", "Benjamín", "Sofía", "Tomás", "Valentina", "Matías", "Florencia", "Juan", "María", "Agustín", "Emilia", "Lucas", "Gabriela", "Diego", "Renata", "José", "Nicolás", "Antonia", "Alejandro", "Lucía", "Pablo", "Paula"],
  "Colombia": ["Santiago", "Valentina", "Mateo", "Isabella", "Tomás", "María José", "Juan David", "Emilia", "Gabriel", "Laura", "Daniel", "Sofía", "Andrés", "Camila", "José", "María", "Sebastián", "Natalia", "Sofía", "Juan", "Manuela", "Alejandro", "Lucía", "Felipe", "Isabel"],
  "Peru": ["Santiago", "Valentina", "Mateo", "Isabella", "Tomás", "María José", "Gabriel", "Camila", "Emilia", "Diego", "Laura", "José", "Andrés", "Sebastián", "María", "Isabela", "Alejandro", "Natalia", "Lucas", "Manuela", "Juan David", "Lucía", "Felipe", "Paula", "Gabriela"],
  "Venezuela": ["Santiago", "Valentina", "Mateo", "Isabella", "Tomás", "Emilia", "Gabriel", "Camila", "Diego", "José", "María", "Andrés", "Natalia", "Lucas", "Sebastián", "Manuela", "Felipe", "Laura", "Isabel", "María José", "Alejandro", "Emilia", "Gabriela", "Juan David", "Lucía"],
  "Ecuador": ["Mateo", "Isabella", "Santiago", "Valentina", "Tomás", "Emilia", "Gabriel", "Camila", "Diego", "Laura", "José", "María", "Andrés", "Sebastián", "Manuela", "Lucas", "Felipe", "Natalia", "Isabel", "Juan David", "María José", "Alejandro", "Gabriela", "Lucía", "Renata"],
  "Uruguay": ["Santiago", "Isabella", "Mateo", "Valentina", "Tomás", "Emilia", "Gabriel", "Camila", "José", "Laura", "Diego", "María", "Andrés", "Lucas", "Manuela", "Natalia", "Felipe", "Isabel", "Sebastián", "María José", "Alejandro", "Gabriela", "Lucía", "Renata", "Juan David"],
  "Bolivia": ["Mateo", "Isabella", "Santiago", "Valentina", "Tomás", "Emilia", "Gabriel", "Camila", "José", "Laura", "Diego", "María", "Andrés", "Lucas", "Manuela", "Natalia", "Felipe", "Sebastián", "Isabel", "María José", "Alejandro", "Gabriela", "Lucía", "Renata", "Juan David"],
  "Paraguay": ["Mateo", "Isabella", "Santiago", "Valentina", "Tomás", "Emilia", "Gabriel", "Camila", "José", "Laura", "Diego", "María", "Andrés", "Lucas", "Manuela", "Natalia", "Felipe", "Sebastián", "Isabel", "María José", "Alejandro", "Gabriela", "Lucía", "Renata", "Juan David"],
  "Guyana": ["Mohamed", "Ayesha", "Jamal", "Sofia", "Ali", "Ravi", "Sharon", "Jai", "Rita", "Iqbal", "Bina", "Ameer", "Ramesh", "Shiva", "Nisha", "Zara", "Ravi", "Asha", "Rohan", "Mina", "Raj", "Kiran", "Suman", "Preeti", "Meena"],
  "Suriname": ["Jansen", "Koeiman", "Schenk", "Alibux", "Loez", "Ramdharie", "Kumar", "Ali", "Aboe", "Jagroep", "Naar", "Hira", "Sookram", "Jankie", "Nisha", "Sanoe", "Ramkhelawan", "Khan", "Ramnarine", "Dewnarain", "Naar", "Jalah", "Hoost", "Sampson", "Sutaran"],
  "French Guiana": ["Liam", "Mia", "Noah", "Emma", "Lucas", "Chloé", "Jules", "Lina", "Arthur", "Manon", "Gabriel", "Alice", "Paul", "Léa", "Louis", "Zoe", "Adam", "Lou", "Hugo", "Sarah", "Ethan", "Jade", "Inès", "Milo", "Louise"],
  "Nigeria": ["Muhammad", "Fatima", "Ahmed", "Aisha", "Ibrahim", "Maryam", "Oluwaseun", "Adebayo", "Ngozi", "Chinedu", "Emmanuel", "Chioma", "Ifeoma", "Olamide", "Tolu", "Bola", "Aisha", "Ife", "Opeyemi", "Jibola", "Oluwafemi", "Ayomide", "Funmi", "Oluwadamilola", "Oluwatobi"],
  "South Africa": ["Sipho", "Zanele", "Thabo", "Nandi", "Lerato", "Sibusiso", "Bongi", "Nomvula", "Mpho", "Nokuthula", "Marlene", "Lindiwe", "Jabulani", "Andile", "Dineo", "Thuli", "Sifiso", "Bongani", "Nkosinathi", "Gugu", "Khanyi", "Zodwa", "Dumisani", "Palesa", "Lwazi"],
  "Kenya": ["David", "Mary", "John", "Elizabeth", "Michael", "Esther", "James", "Grace", "Peter", "Hannah", "Paul", "Alice", "Daniel", "Beatrice", "Joseph", "Sarah", "Samuel", "Margaret", "Anthony", "Alice", "Kevin", "Joyce", "Gideon", "Wanjiku", "Nancy"],
  "Ghana": ["Kwame", "Akosua", "Kofi", "Abena", "Kojo", "Afia", "Kwabena", "Esi", "Yaw", "Akua", "Abena", "Kwaku", "Akua", "Kofi", "Afia", "Kwaku", "Esi", "Ama", "Yaw", "Abena", "Kofi", "Akosua", "Kojo", "Kwame", "Ama"],
  "Ethiopia": ["Amanuel", "Mulu", "Tadesse", "Mulu", "Hailu", "Kebede", "Girma", "Amsalu", "Fikre", "Wondimu", "Beyene", "Mekdes", "Tefera", "Ayele", "Bekele", "Biru", "Abebe", "Fasil", "Hanna", "Mekonnen", "Mihret", "Mekdes", "Mulu", "Biruk", "Hailu"],
  "Uganda": ["Moses", "Mary", "John", "Elizabeth", "Peter", "Sarah", "David", "Hannah", "James", "Jane", "Paul", "Rebecca", "Samuel", "Grace", "Isaac", "Anna", "Joseph", "Joyce", "Gideon", "Margaret", "Joshua", "Betty", "Daniel", "Esther", "Helen"],
  "Tanzania": ["Juma", "Amani", "Fatima", "Musa", "Asha", "Abdallah", "Hawa", "Juma", "Salma", "Mariam", "Ahmed", "Mwanahawa", "Mariam", "Mohamed", "Mwanaidi", "Hassan", "Rashida", "Samson", "Ismail", "Amani", "Moses", "Jabir", "Anna", "Zuberi", "Fatima"],
  "Zimbabwe": ["Tendai", "Chipo", "Tinashe", "Kudzai", "Rutendo", "Nyasha", "Rufaro", "Munyati", "Tatenda", "Memory", "Nhlanhla", "Tapiwa", "Tariro", "Blessing", "Farai", "Makanaka", "Ngoni", "Mudiwa", "Munyaradzi", "Kudzai", "Rumbidzai", "Samantha", "Tanyaradzwa", "Shamiso", "Tsitsi"],
  "Rwanda": ["Eric", "Jeanne", "Emmanuel", "Yvonne", "Jean", "Chantal", "Claude", "Alice", "David", "Marie", "Sylvain", "Odette", "Jean-Pierre", "Emeline", "Jean-Claude", "Monique", "Antoine", "Patricia", "Clement", "Grace", "Paul", "Julienne", "Daniel", "Aline"],
  "Burundi": ["Jean", "Marie", "Pierre", "Chantal", "Luc", "Monique", "François", "Eloïse", "Philippe", "Julienne", "Benoît", "Christine", "Robert", "Alice", "Elie", "Sylvie", "Patrick", "Claudine", "Joseph", "Gabrielle", "Jacques", "Magdalene", "Antoine", "Pauline"],
  "Somalia": ["Mohamed", "Aisha", "Abdi", "Fatima", "Ahmed", "Hassan", "Maryam", "Ismail", "Yusuf", "Hawa", "Ali", "Nadia", "Omar", "Amin", "Rashida", "Yusuf", "Ibrahim", "Mohamed", "Khadija", "Saida", "Ali", "Fadumo", "Hassan", "Asha", "Adan"],
  "South Sudan": ["Amin", "Fatima", "Hassan", "Mohamed", "Ali", "Yusuf", "Ibrahim", "Maryam", "Mohamud", "Abdullah", "Rashida", "Omar", "Hawa", "Khalid", "Saida", "Hussein", "Asha", "Mohammed", "Hassan", "Yassin", "Nur", "Faduma", "Amin", "Nadia", "Rashid"],
  "Central African Republic": ["Paul", "Marie", "Jean", "Claudine", "Pierre", "Eloise", "Adele", "Antoine", "Rose", "Jacques", "Françoise", "Bernard", "Jeanne", "Joseph", "Gabrielle", "Sylvie", "Robert", "Monique", "Emmanuel", "Julienne", "Martin", "Germaine", "Elisabeth", "Berthe"],
  "Ivory Coast": ["Koffi", "N'Guessan", "Yao", "Kouadio", "Samantha", "Koné", "Ouatara", "Fadiga", "Koffi", "Yapi", "Moussa", "Kouame", "Diatta", "Koffi", "Kouadio", "N'Guessan", "Diomandé", "Fofana", "Mariam", "N'Guessan", "Niamkey", "Kouamé", "Yao", "Fofana", "Kouadio"],
  "Gabon": ["Ona", "Mebey", "Nzeng", "Eteki", "Momo", "Ngoma", "Moukou", "Moukou", "Ongong", "Obiang", "Nze", "Bongo", "Koumba", "Mokogo", "Momo", "Nguema", "Eteki", "Mombom", "Ngouma", "Nzeng", "Mebey", "Moukou", "Nze", "Koumba", "Mokogo"],
  "Equatorial Guinea": ["Obiang", "Nchama", "Nguema", "Esono", "Mba", "Ongong", "Boma", "Eteki", "Mokogo", "Mbeng", "Mba", "Moukou", "Mokogo", "Nzeng", "Mokogo", "Asebo", "Mokogo", "Ngon", "Momo", "Dibang", "Eteki", "Nzasu", "Nchama", "Mokogo"],
  "Sierra Leone": ["Moses", "Fatima", "John", "Elizabeth", "James", "Mary", "David", "Alice", "Paul", "Sarah", "William", "Rebecca", "Michael", "Hannah", "Joseph", "Joyce", "Samuel", "Esther", "Daniel", "Margaret", "Charles", "Victoria", "Abdullah", "Betty", "Andrew"],
  "Liberia": ["James", "Mary", "John", "Elizabeth", "William", "Sarah", "David", "Alice", "Paul", "Hannah", "Michael", "Rebecca", "Samuel", "Joyce", "Joseph", "Margaret", "Daniel", "Esther", "Charles", "Betty", "Richard", "Grace", "Peter", "Helen", "Frank"],
  "Mauritius": ["Sanjay", "Mina", "Raj", "Aarti", "Kiran", "Amit", "Sita", "Ravi", "Asha", "Prakash", "Geeta", "Amit", "Sanjay", "Sunita", "Rohit", "Nisha", "Kumar", "Poonam", "Anil", "Rekha", "Meena", "Ravi", "Suman", "Rajesh", "Usha"],
  "Malawi": ["Chimwemwe", "Mary", "John", "Elizabeth", "David", "Grace", "Peter", "Alice", "Samuel", "Sarah", "Michael", "Esther", "Joseph", "Margaret", "Paul", "Hannah", "William", "Nancy", "James", "Joyce", "Daniel", "Dorothy", "Chifundo", "Martha", "Henry"],
  "Egypt": ["Mohamed", "Ahmed", "Hassan", "Ali", "Ibrahim", "Fatima", "Aisha", "Sara", "Mariam", "Hussein", "Nadia", "Khaled", "Amr", "Yasmin", "Noha", "Dina", "Reem", "Rania", "Mona", "Layla", "Mahmoud", "Nour", "Salma", "Hossam", "Ramy"],
  "Morocco": ["Mohamed", "Fatima", "Ahmed", "Aicha", "Hassan", "Khalid", "Youssef", "Nadia", "Rachid", "Souad", "Mouna", "Samira", "Ibrahim", "Meryem", "Omar", "Zineb", "Mouna", "Rachida", "Imane", "Siham", "Hassan", "Mohammed", "Khadija", "Sofia", "Fatiha"],
  "Algeria": ["Mohamed", "Fatima", "Ahmed", "Khadija", "Ali", "Sofia", "Yasmine", "Ahmed", "Rachid", "Mounia", "Sofiane", "Karim", "Sabrina", "Nadia", "Said", "Khaled", "Amina", "Rami", "Nassima", "Samira", "Omar", "Rachida", "Mohamed", "Samir", "Nassima"],
  "Tunisia": ["Mohamed", "Fatima", "Ali", "Khadija", "Ahmed", "Mariam", "Salah", "Khalil", "Nadia", "Rania", "Youssef", "Rami", "Amel", "Khaled", "Mouna", "Zied", "Sonia", "Sofiane", "Nour", "Amina", "Hussein", "Sana", "Mounir", "Sabrina", "Hiba"],
  "Libya": ["Mohamed", "Fatima", "Ahmed", "Ali", "Khadija", "Hassan", "Nadia", "Omar", "Aisha", "Rania", "Khalid", "Yasmine", "Moussa", "Hussain", "Khalifa", "Sami", "Rashida", "Mona", "Mohammed", "Sara", "Amal", "Ibrahim", "Layla", "Samira", "Mohamed"],
  "Mauritania": ["Mohamed", "Fatima", "Omar", "Aicha", "Ahmed", "Mouhamed", "Ramatou", "Moussa", "Mariama", "Baba", "Said", "Fatimata", "Sidi", "Oumou", "Mohamed", "Bintou", "Salem", "Aminata", "Ould", "Maimouna", "Abdallah", "Hawa", "Ismail", "Hassan", "Mouhamed"],
  "Western Sahara": ["Mohamed", "Fatima", "Ahmed", "Aicha", "Omar", "Rachid", "Moussa", "Khadija", "Hassan", "Nadia", "Mouna", "Said", "Mariam", "Youssef", "Sonia", "Salma", "Sofia", "Khalid", "Rania", "Ibrahim", "Amar", "Nassira", "Aminata", "Samira", "Rami"],
  "Sudan": ["Mohamed", "Fatima", "Ahmed", "Ali", "Mariam", "Aisha", "Omar", "Rania", "Khalid", "Nadia", "Hassan", "Rashida", "Sara", "Ibrahim", "Layla", "Abdallah", "Hassan", "Sofia", "Amal", "Mounir", "Khadija", "Mohamed", "Amin", "Samira", "Salma"],
  "USA": ["James", "Mary", "John", "Patricia", "Robert", "Jennifer", "Michael", "Linda", "William", "Elizabeth", "David", "Barbara", "Richard", "Susan", "Joseph", "Jessica", "Charles", "Sarah", "Thomas", "Karen", "Daniel", "Nancy", "Matthew", "Helen", "Andrew"],
  "Israel": ["David", "Miriam", "Yosef", "Rivka", "Avraham", "Sara", "Micha", "Esther", "Yaakov", "Rachel", "Daniel", "Chana", "Michael", "Leah", "Joseph", "Hannah", "Samuel", "Naomi", "Isaac", "Tamar", "Eliezer", "Shoshana", "Benjamin", "Ruth", "Shimon"],
  "China": ["Liu", "Chen", "Wang", "Li", "Yang", "Zhang", "Huang", "Zhao", "Wu", "Xu", "Sun", "Ma", "Guo", "Lin", "He", "Liao", "Luo", "Peng", "Jiang", "Xie", "Hsu", "Deng", "Cai", "Yuan"],
  "India": ["Aarav", "Vivaan", "Aditya", "Vihaan", "Arjun", "Sai", "Reyansh", "Aadhya", "Ananya", "Kavya", "Saanvi", "Ishaan", "Aanya", "Aarav", "Aadhya", "Aryan", "Karthik", "Siddharth", "Tanvi", "Pranav", "Rohan", "Ishaan", "Maya", "Alok"],
  "Japan": ["Haruto", "Yuto", "Sota", "Hiroshi", "Riku", "Yuki", "Kaito", "Ryo", "Kenta", "Taichi", "Shunya", "Ryota", "Sakura", "Hina", "Yui", "Rina", "Miku", "Saki", "Hinata", "Yuka", "Aoi", "Natsuki", "Kana", "Moe"],
  "South Korea": ["Joon", "Jin", "Min", "Hyun", "Jae", "Ji", "Seok", "Yoon", "Soo", "Jung", "Hyun", "Ji", "Min", "Seok", "Jae", "Hoon", "Kyung", "In", "Dong", "Sung", "Yun", "Chan", "Ki", "Woo", "Soo"],
  "Vietnam": ["Nguyen", "Trung", "Thao", "Anh", "Hanh", "Tuan", "Duc", "Mai", "Hanh", "Lan", "Quang", "Trinh", "Hoa", "Minh", "Huyen", "Phuong", "Nhat", "Binh", "Tung", "Thu", "Lam", "Thuy", "Chau", "Khanh", "Tam"],
  "Thailand": ["Nattapong", "Pongpat", "Supachai", "Chaiwat", "Somchai", "Apichart", "Sarawut", "Wisit", "Santi", "Kiat", "Nattawut", "Somphong", "Wuttichai", "Yuthana", "Chirath", "Nattapong", "Kanok", "Pongsak", "Chokchai", "Teerawat", "Jirawat", "Pongkan", "Somchai", "Phuchit", "Kittipong"],
  "Malaysia": ["Ahmad", "Mohamad", "Siti", "Roslan", "Wan", "Kamaruddin", "Mokhtar", "Ismail", "Yusof", "Hafiz", "Zainab", "Aziz", "Khadijah", "Abdul", "Latifah", "Siti", "Nor", "Samsudin", "Rahman", "Mansor", "Sharifah", "Shamsul", "Halim", "Nordin"],
  "Singapore": ["Jie", "Wei", "Hui", "Xiao", "Shan", "Lin", "Yi", "Mei", "Li", "Hao", "Jia", "Xuan", "Cheng", "Kai", "Ling", "Yong", "Fang", "Qin", "Jin", "Shu", "Lian", "Yan", "Yu", "Ling"],
  "Indonesia": ["Ahmad", "Budi", "Dewi", "Sari", "Siti", "Rina", "Rudi", "Putri", "Soleh", "Joko", "Ratna", "Andi", "Yuli", "Hadi", "Arif", "Yanti", "Fitri", "Novi", "Dedi", "Eka", "Nur", "Hadi", "Santi", "Tri"],
  "Philippines": ["Juan", "Maria", "Jose", "Ana", "Rafael", "Luis", "Margarita", "Antonio", "Rosario", "Emilio", "Carlos", "Luz", "Isabel", "Manuel", "Carmen", "Fernando", "Teresa", "Josefina", "Ricardo", "Concepcion", "Salvador", "Veronica", "Gregorio", "Elena"],
  "Saudi Arabia": ["Mohammed", "Ahmed", "Ali", "Hassan", "Abdullah", "Faisal", "Khalid", "Sultan", "Yousef", "Saad", "Omar", "Nasser", "Salman", "Ayman", "Majed", "Fahad", "Rashed", "Zaid", "Abdulrahman", "Badr", "Tariq", "Nawaf", "Saud", "Hussain"],
  "United Arab Emirates": ["Mohammed", "Ahmed", "Ali", "Hassan", "Abdullah", "Khalid", "Faisal", "Saif", "Yousef", "Hamad", "Nasser", "Sultan", "Rashed", "Majed", "Omar", "Zaid", "Salem", "Hussain", "Tariq", "Saeed", "Fahad", "Mubarak", "Khalifa", "Hussain"],
  "Qatar": ["Mohammed", "Ahmed", "Ali", "Hassan", "Abdullah", "Nasser", "Khalid", "Saif", "Yousef", "Omar", "Sultan", "Rashed", "Majed", "Faisal", "Salem", "Hussain", "Zaid", "Tariq", "Saad", "Hamad", "Fahad", "Mubarak", "Khalifa", "Jassim"],
  "Kuwait": ["Mohammed", "Ahmed", "Ali", "Hassan", "Abdullah", "Khalid", "Faisal", "Nasser", "Saif", "Yousef", "Omar", "Rashed", "Majed", "Hussain", "Zaid", "Salem", "Tariq", "Fahad", "Mubarak", "Hamad", "Khalifa", "Ayman", "Jassim", "Nawaf"],
  "Oman": ["Mohammed", "Ahmed", "Ali", "Hassan", "Abdullah", "Khalid", "Faisal", "Nasser", "Yousef", "Omar", "Rashed", "Majed", "Salem", "Hussain", "Saif", "Tariq", "Zaid", "Fahad", "Hamad", "Mubarak", "Khalifa", "Nawaf", "Jassim", "Ayman"],
  "Jordan": ["Mohammed", "Ahmed", "Ali", "Hassan", "Abdullah", "Yousef", "Khalid", "Omar", "Faisal", "Majed", "Nasser", "Salem", "Rashed", "Hussain", "Saif", "Zaid", "Tariq", "Fahad", "Mubarak", "Jassim", "Hamad", "Ayman", "Khalifa", "Nawaf"],
  "Lebanon": ["Mohammed", "Ali", "Hassan", "Jad", "Rami", "Samir", "Nabil", "Adel", "Fares", "Ziad", "Mounir", "George", "Rana", "Sami", "Nadine", "Youssef", "Jad", "Rita", "Miriam", "Salim", "Fadi", "Rami", "Elie", "Fouad"],
  "Syria": ["Mohammed", "Ali", "Hassan", "Omar", "Abdullah", "Youssef", "Fares", "Rami", "Ziad", "Khaled", "Salim", "Nasser", "Rashed", "Hussein", "Tariq", "Jad", "Jamal", "Ahmad", "Nabil", "Fouad", "Sami", "Fadi", "Mounir", "Ayman"],
  "Iraq": ["Mohammed", "Ahmed", "Ali", "Hassan", "Omar", "Abdullah", "Khalid", "Youssef", "Faisal", "Rashed", "Salim", "Jassim", "Tariq", "Nasser", "Majed", "Hussein", "Jad", "Zaid", "Fouad", "Nabil", "Rami", "Ahmad", "Fadi", "Ayman"],
  "Bahrain": ["Mohammed", "Ahmed", "Ali", "Hassan", "Abdullah", "Khalid", "Nasser", "Faisal", "Yousef", "Omar", "Majed", "Salem", "Hussain", "Tariq", "Zaid", "Rashed", "Fahad", "Mubarak", "Khalifa", "Jassim", "Ayman", "Nawaf", "Fouad", "Jad"],
  "Yemen": ["Mohammed", "Ali", "Ahmed", "Hassan", "Abdullah", "Omar", "Youssef", "Khalid", "Faisal", "Rashed", "Nasser", "Majed", "Hussain", "Salem", "Tariq", "Zaid", "Mubarak", "Hamad", "Ayman", "Fouad", "Jassim", "Rami", "Ahmad", "Jad"],
  "Iran": ["Mohammad", "Ali", "Hassan", "Reza", "Fatemeh", "Zahra", "Saeid", "Mahdi", "Leila", "Arezoo", "Ahmad", "Neda", "Sara", "Parisa", "Ali", "Ehsan", "Mina", "Yasmin", "Mostafa", "Roya", "Shirin", "Mohsen", "Maryam", "Javad"],
  "Australia": ["Oliver", "Charlotte", "Jack", "Amelia", "Noah", "Isla", "William", "Ava", "Leo", "Mia", "Henry", "Sophia", "George", "Lily", "Thomas", "Ella", "Jack", "Olivia", "James", "Zoe", "Alexander", "Grace", "Ethan", "Emily", "Benjamin"],
  "New Zealand": ["Oliver", "Isla", "Jack", "Charlotte", "Liam", "Ava", "Noah", "Amelia", "George", "Mia", "Harry", "Sophie", "James", "Ella", "William", "Chloe", "Leo", "Olivia", "Lucas", "Zoe", "Thomas", "Grace", "Henry", "Ruby"],
  "Canada": ["Liam", "Olivia", "Noah", "Emma", "Jackson", "Charlotte", "Aiden", "Amelia", "Ethan", "Sophia", "Lucas", "Isabella", "Benjamin", "Mia", "Henry", "Avery", "Sebastian", "Ella", "James", "Abigail", "Oliver", "Harper", "Alexander", "Grace", "Daniel"],
  "Mexico": ["Sofía", "Mateo", "Camila", "Santiago", "Valentina", "Diego", "Ximena", "Alejandro", "Valeria", "Sebastián", "Mariana", "José", "Natalia", "Daniel", "Isabella", "Gabriel", "Aitana", "Carlos", "Lucía", "Luis", "Paola", "Jorge", "Renata", "Miguel", "Laura"],
  "Guatemala": ["Mateo", "Sofía", "Camila", "José", "Valentina", "Diego", "Ximena", "Alejandro", "Mariana", "Sebastián", "Daniel", "Isabella", "Gabriel", "Natalia", "Luis", "Santiago", "Paola", "Adriana", "Lucía", "Jorge", "Renata", "Carlos", "Laura", "Andrés"],
  "Costa Rica": ["Sofía", "Mateo", "Valentina", "Diego", "Camila", "José", "Mariana", "Sebastián", "Isabella", "Daniel", "Gabriel", "Natalia", "Alejandro", "Ximena", "Luis", "Renata", "Santiago", "Laura", "Carlos", "Lucía", "José Luis", "Paola", "Santiago", "Andrés", "Emma"],

};

